# Define default settings that will be applied to all services
x-service-defaults: &service-defaults
  restart: "no"
  deploy:
    restart_policy:
      condition: "none"
  labels:
    - "com.docker.compose.rm=true"

volumes:
  ql_dvol:

    ## TODO
    ## Add profiles:   getAndIndex and serveIndex  and combine (or not) the two compose files

services:
  volume-setup:   ##  TODO, this is likely not need, change to the "list content" service
    <<: *service-defaults
    image: alpine:latest
    volumes:
      - ql_dvol:/data
    command: chown -R 1000:1000 /data
    user: root

  downloader:
    <<: *service-defaults
    image: alpine/curl
    depends_on:
      volume-setup:
        condition: service_completed_successfully
    user: "1000:1000"  # Add this line to run as the same user
    volumes:
      - ql_dvol:/data
    command: >
      sh -c "curl -fLo /data/Qleverfile.odis http://ossapi.oceaninfohub.org/public/Qleverfile-odis &&
             ls /data && echo 'File Qleverfile.odis downloaded successfully to /data/'"

  getdata:
    <<: *service-defaults
    image: adfreiburg/qlever:latest
    depends_on:
      downloader:
        condition: service_completed_successfully
    user: "1000:1000"
    volumes:
      - ql_dvol:/data
    working_dir: /data
    command: ["qlever -q Qleverfile.odis get-data"]
    stdin_open: true
    tty: true

  jsonsetup:
    <<: *service-defaults
    image: alpine:latest
    depends_on:
      getdata:
        condition: service_completed_successfully
    volumes:
      - ql_dvol:/data
    working_dir: /data
    command: "echo '{ \"ascii-prefixes-only\": false, \"num-triples-per-batch\": 100000 }' > /odis.settings.json"
    user: root

  indexer:
    <<: *service-defaults
    image: adfreiburg/qlever:latest
    depends_on:
      jsonsetup:
        condition: service_completed_successfully
    user: "1000:1000"
    volumes:
      - ql_dvol:/data
    working_dir: /data
    command: [ "cat /data/odis.nq | IndexBuilderMain -i odis -s /data/odis.settings.json -F nq -f - | tee odis.index-log.txt" ]
    stdin_open: true
    tty: true