PREFIX pathSearch: <https://qlever.cs.uni-freiburg.de/pathSearch/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ql: <http://qlever.cs.uni-freiburg.de/builtin-functions/>


SELECT ?start ?pred ?end ?source ?path ?edge ?target WHERE {

  SERVICE pathSearch: {
    _:path pathSearch:algorithm pathSearch:allPaths ;
           pathSearch:source ?source ;
           pathSearch:target ?target ;
		   pathSearch:edgeProperty ?pred ;

           pathSearch:pathColumn ?path ;
           pathSearch:edgeColumn ?edge ;
           pathSearch:start ?start ;
           pathSearch:end ?end ;
    {
      SELECT * WHERE {
        ?start ?pred ?end .

      }
    }
  }
}

