PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX ql: <http://qlever.cs.uni-freiburg.de/builtin-functions/>
SELECT * {
  BIND (ql:isGeoPoint("POINT(125.726 28.5262)"^^geo:wktLiteral) AS ?gp) # true
  BIND (ql:isGeoPoint(STRDT("POINT(125.726 28.5262)",geo:wktLiteral)) AS ?gp2) # false
  BIND (DATATYPE("POINT(125.726 28.5262)"^^geo:wktLiteral) as ?dtpoint)
  BIND (DATATYPE(STRDT("POINT(125.726 28.5262)",geo:wktLiteral)) as ?dtpoint2)
  BIND (geof:distance( "POINT(125.726 28.5262)"^^geo:wktLiteral, "POINT(125.726 28.5262)"^^geo:wktLiteral) as ?distance )
  BIND (geof:distance( STRDT("POINT(125.726 28.5262)",geo:wktLiteral),"POINT(125.726 28.5262)"^^geo:wktLiteral ) as ?distance_strdt )
}
