PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
prefix sschema: <https://schema.org/>
PREFIX ql: <http://qlever.cs.uni-freiburg.de/builtin-functions/>

SELECT distinct *
WHERE {
    ?subj ?o ?item .
    ?text ql:contains-entity ?item .
    ?text ql:contains-word "water"
}
LIMIT 1000

